### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Phabr1945** [AtomicGamer9523/DumbDB#1]
Are we b=making this from scratch? Also, very good channel for info: https://www.youtube.com/c/CMUDatabaseGroup/playlists

**Comment by Phabr1945** [comment]
also, the clear command should be able to have an argument all to clear everything, or range to clear a range of keys, or an except to clear all but some keys
EX:
clear range 14938, 3yu3i, nf83n, 3329h
clear all except 289hd, 478fs
clear all

**Comment by AtomicGamer9523** [comment]
Yes, we will be making this from scratch, I have started working on the rust implementation (I will also add Python and JS bindings)
